import Logo from "@/shared/components/Logo";
import Footer from "@/shared/components/Footer";

export default function TermsPage() {
  return (
    <div className="flex min-h-screen flex-col">
      <header className="border-b border-slate-200 px-6 py-4">
        <a href="/login"><Logo /></a>
      </header>
      <main className="mx-auto max-w-2xl flex-1 px-6 py-10 text-sm text-slate-600">
        <h1 className="mb-1 text-2xl font-bold text-slate-900">Terms of Service</h1>
        <p className="mb-6 text-xs text-slate-400">Last updated: 2026</p>

        <p className="mb-4">
          By creating an account and using FinSight AI, you agree to these Terms of Service.
          FinSight AI is a decision-support tool for small and medium businesses and does not
          replace professional financial, tax, or legal advice.
        </p>
        <p className="mb-4">
          You are responsible for the accuracy of the financial data you upload. Predictions and
          risk scores generated by the platform are estimates based on the data provided and
          should be interpreted as guidance, not guarantees.
        </p>
        <p>
          We may update these terms as the platform evolves. Continued use of the service after
          changes are published constitutes acceptance of the updated terms.
        </p>
      </main>
      <Footer />
    </div>
  );
}